r1:
	gcc ex01.c -o app && ./app

r2:
	gcc ex02.c -o app && ./app

r3:
	gcc ex03.c -o app && ./app

r4:
	gcc ex04.c -o app && ./app

r5:
	gcc ex05.c -o app && ./app

r6:
	gcc ex06.c -o app && ./app

r7:
	gcc ex07.c -o app && ./app

r8:
	gcc ex08.c -o app && ./app

r9:
	gcc ex09.c -o app && ./app

r10:
	gcc ex10.c -o app && ./app

